/**
 * Demo/sample AI analysis + complaint content, keyed by problem category.
 *
 * IMPORTANT: none of this is generated by a real AI model. Used in two
 * places only: (1) the static, unauthenticated sample-issue detail pages
 * (src/lib/sample-data.ts), and (2) as a fallback for real reports whose
 * AI analysis predates the Phase 6A complaint-generation fields (or whose
 * AI analysis never completed) — see src/app/report/complaint/page.tsx.
 * Every real, AI-analyzed report now gets its complaint subject/impact/
 * action from the live Gemini response (src/lib/ai.ts) instead. Telugu
 * fields stay templated everywhere — no translation provider is
 * configured (BLOCKED, see docs/PHASE_6A_REPORT.md).
 */
import type { Priority, ProblemCategory } from "./types";

export interface ComplaintTextSet {
  subject: string;
  description: string;
  impact: string;
  action: string;
}

export interface CategoryAIPreset {
  problemLabel: string;
  priority: Priority;
  severity: number;
  confidence: number;
  departmentLabel: string;
  department: string;
  inCharge: string;
  explanationEn: string;
  explanationTe: string;
  complaintEn: ComplaintTextSet;
  complaintTe: ComplaintTextSet;
}

export const categoryAIPresets: Record<ProblemCategory, CategoryAIPreset> = {
  ROAD: {
    problemLabel: "Pothole Detected",
    priority: "HIGH",
    severity: 82,
    confidence: 92,
    departmentLabel: "Municipal Roads Department",
    department: "Roads",
    inCharge: "Roads Department — Area In-charge",
    explanationEn:
      "The image shows significant road surface damage that may create safety risks for vehicles and pedestrians.",
    explanationTe:
      "చిత్రంలో వాహనాలు మరియు పాదచారులకు భద్రతా ప్రమాదాన్ని కలిగించే గణనీయమైన రోడ్డు ఉపరితల నష్టం కనిపిస్తోంది.",
    complaintEn: {
      subject: "Request for repair of road pothole",
      description:
        "A pothole has formed on the road surface, posing a risk to vehicles and pedestrians, especially during night hours and rain.",
      impact: "Increased risk of accidents, vehicle damage, and traffic slowdown.",
      action: "Immediate inspection and repair of the affected road surface by the Municipal Roads Department.",
    },
    complaintTe: {
      subject: "రోడ్డు గుంత మరమ్మతు కోసం అభ్యర్థన",
      description:
        "రోడ్డు ఉపరితలంపై గుంత ఏర్పడింది, ఇది ముఖ్యంగా రాత్రి వేళల్లో మరియు వర్షం సమయంలో వాహనాలు మరియు పాదచారులకు ప్రమాదకరంగా మారింది.",
      impact: "ప్రమాదాల ప్రమాదం, వాహన నష్టం మరియు ట్రాఫిక్ ఆలస్యం పెరుగుతుంది.",
      action: "మున్సిపల్ రోడ్స్ విభాగం దెబ్బతిన్న రహదారి ఉపరితలాన్ని తక్షణమే తనిఖీ చేసి మరమ్మతు చేయాలి.",
    },
  },
  GARBAGE: {
    problemLabel: "Garbage Overflow Detected",
    priority: "MEDIUM",
    severity: 58,
    confidence: 89,
    departmentLabel: "Municipal Sanitation Department",
    department: "Sanitation",
    inCharge: "Sanitation Department — Ward Supervisor",
    explanationEn:
      "The image shows an overflowing waste bin with uncollected garbage, creating a sanitation and health hazard.",
    explanationTe:
      "చిత్రంలో నిండిపోయిన చెత్త బుట్ట మరియు సేకరించని వ్యర్థాలు కనిపిస్తున్నాయి, ఇది పరిశుభ్రత మరియు ఆరోగ్య ప్రమాదాన్ని కలిగిస్తుంది.",
    complaintEn: {
      subject: "Request for garbage collection and bin servicing",
      description:
        "Garbage has accumulated and is overflowing from the collection bin, creating unsanitary conditions in the area.",
      impact: "Foul odor, pest attraction, and health risk to nearby residents.",
      action: "Prompt garbage collection and regular servicing of the bin by the Sanitation Department.",
    },
    complaintTe: {
      subject: "చెత్త సేకరణ మరియు బుట్ట సేవ కోసం అభ్యర్థన",
      description: "చెత్త బుట్ట నిండిపోయి పరిసర ప్రాంతంలో అపరిశుభ్ర పరిస్థితులు ఏర్పడ్డాయి.",
      impact: "దుర్వాసన, పురుగుల బెడద మరియు సమీప నివాసితులకు ఆరోగ్య ప్రమాదం.",
      action: "సానిటేషన్ విభాగం వెంటనే చెత్తను సేకరించి బుట్టను క్రమం తప్పకుండా సేవించాలి.",
    },
  },
  DRAINAGE: {
    problemLabel: "Drainage Blockage Detected",
    priority: "CRITICAL",
    severity: 88,
    confidence: 90,
    departmentLabel: "Municipal Drainage Department",
    department: "Drainage",
    inCharge: "Drainage Department — Zone Engineer",
    explanationEn:
      "The image shows stagnant or overflowing water from a blocked storm drain, which can cause flooding and breed disease-carrying mosquitoes.",
    explanationTe:
      "చిత్రంలో మూసుకుపోయిన డ్రైనేజీ నుండి నిలిచిపోయిన లేదా పొంగిపొర్లుతున్న నీరు కనిపిస్తోంది, ఇది వరదలకు మరియు దోమల వృద్ధికి కారణమవుతుంది.",
    complaintEn: {
      subject: "Request for clearing of blocked storm drain",
      description:
        "Water is stagnating and overflowing from a blocked drain, creating a flooding and mosquito-breeding hazard.",
      impact: "Risk of waterlogging, road damage, and mosquito-borne disease.",
      action: "Urgent clearing and desilting of the drain by the Drainage Department.",
    },
    complaintTe: {
      subject: "మూసుకుపోయిన డ్రైనేజీ శుభ్రం చేయడానికి అభ్యర్థన",
      description:
        "మూసుకుపోయిన డ్రైనేజీ నుండి నీరు నిలిచిపోయి పొంగిపొర్లుతోంది, ఇది వరద మరియు దోమల ప్రమాదాన్ని కలిగిస్తుంది.",
      impact: "నీరు నిలిచిపోవడం, రోడ్డు నష్టం మరియు దోమల ద్వారా వ్యాపించే వ్యాధుల ప్రమాదం.",
      action: "డ్రైనేజీ విభాగం వెంటనే డ్రైన్‌ను శుభ్రం చేసి పూడిక తీయాలి.",
    },
  },
  STREETLIGHT: {
    problemLabel: "Streetlight Malfunction Detected",
    priority: "MEDIUM",
    severity: 45,
    confidence: 87,
    departmentLabel: "Municipal Electrical Department",
    department: "Electrical",
    inCharge: "Electrical Department — Maintenance In-charge",
    explanationEn:
      "The image shows a non-functional streetlight, reducing visibility and safety on the street after dark.",
    explanationTe:
      "చిత్రంలో పనిచేయని వీధి దీపం కనిపిస్తోంది, ఇది చీకటి పడిన తర్వాత వీధిలో దృశ్యమానతను మరియు భద్రతను తగ్గిస్తుంది.",
    complaintEn: {
      subject: "Request for repair of non-functional streetlight",
      description: "The streetlight in this area has stopped working, leaving the street dark and unsafe at night.",
      impact: "Reduced visibility and increased safety risk for pedestrians and vehicles at night.",
      action: "Inspection and repair of the streetlight by the Electrical Department.",
    },
    complaintTe: {
      subject: "పనిచేయని వీధి దీపం మరమ్మతు కోసం అభ్యర్థన",
      description:
        "ఈ ప్రాంతంలోని వీధి దీపం పనిచేయడం మానేసింది, రాత్రి వేళల్లో వీధి చీకటిగా మరియు అసురక్షితంగా మారింది.",
      impact: "రాత్రి వేళల్లో దృశ్యమానత తగ్గడం మరియు పాదచారులు, వాహనాలకు భద్రతా ప్రమాదం పెరగడం.",
      action: "ఎలక్ట్రికల్ విభాగం వీధి దీపాన్ని తనిఖీ చేసి మరమ్మతు చేయాలి.",
    },
  },
  WATER_LEAKAGE: {
    problemLabel: "Water Pipeline Leakage Detected",
    priority: "HIGH",
    severity: 74,
    confidence: 91,
    departmentLabel: "Municipal Water Supply Department",
    department: "Water Supply",
    inCharge: "Water Supply Department — Field Engineer",
    explanationEn:
      "The image shows water leaking from a pipeline onto the street, wasting a public resource and damaging the road surface.",
    explanationTe:
      "చిత్రంలో పైప్‌లైన్ నుండి నీరు వీధిలోకి లీకవుతున్నట్లు కనిపిస్తోంది, ఇది ప్రజా వనరును వృథా చేస్తూ రోడ్డు ఉపరితలాన్ని దెబ్బతీస్తుంది.",
    complaintEn: {
      subject: "Request for repair of leaking water pipeline",
      description:
        "Water is leaking from a damaged pipeline and flowing onto the street, wasting water and weakening the road surface.",
      impact: "Water wastage, slippery road surface, and potential road damage over time.",
      action: "Immediate leak repair by the Water Supply Department.",
    },
    complaintTe: {
      subject: "నీటి పైప్‌లైన్ లీకేజీ మరమ్మతు కోసం అభ్యర్థన",
      description:
        "దెబ్బతిన్న పైప్‌లైన్ నుండి నీరు లీకై వీధిలోకి ప్రవహిస్తోంది, నీటిని వృథా చేస్తూ రోడ్డును బలహీనపరుస్తోంది.",
      impact: "నీటి వృథా, జారుడు రోడ్డు ఉపరితలం మరియు కాలక్రమేణా రోడ్డు నష్టం.",
      action: "వాటర్ సప్లై విభాగం వెంటనే లీకేజీని మరమ్మతు చేయాలి.",
    },
  },
  SEWAGE: {
    problemLabel: "Sewage Overflow Detected",
    priority: "CRITICAL",
    severity: 85,
    confidence: 88,
    departmentLabel: "Municipal Sanitation Department",
    department: "Sanitation",
    inCharge: "Sanitation Department — Sewage Maintenance In-charge",
    explanationEn:
      "The image shows sewage overflow in a public area, presenting a serious health and hygiene hazard.",
    explanationTe:
      "చిత్రంలో బహిరంగ ప్రదేశంలో మురుగు నీరు పొంగిపొర్లుతున్నట్లు కనిపిస్తోంది, ఇది తీవ్రమైన ఆరోగ్య మరియు పరిశుభ్రత ప్రమాదాన్ని కలిగిస్తుంది.",
    complaintEn: {
      subject: "Request for urgent sewage overflow cleanup",
      description: "Sewage is overflowing into a public area, creating a serious health and hygiene hazard for residents.",
      impact: "Serious health risk, foul odor, and contamination of the surrounding area.",
      action: "Emergency cleanup and sewage line repair by the Sanitation Department.",
    },
    complaintTe: {
      subject: "అత్యవసర మురుగు నీటి పొంగిపొర్లు శుభ్రపరచడానికి అభ్యర్థన",
      description: "మురుగు నీరు బహిరంగ ప్రదేశంలోకి పొంగిపొర్లి తీవ్రమైన ఆరోగ్య మరియు పరిశుభ్రత ప్రమాదాన్ని కలిగిస్తోంది.",
      impact: "తీవ్రమైన ఆరోగ్య ప్రమాదం, దుర్వాసన మరియు పరిసర ప్రాంత కాలుష్యం.",
      action: "సానిటేషన్ విభాగం అత్యవసరంగా శుభ్రపరచి మురుగు లైన్‌ను మరమ్మతు చేయాలి.",
    },
  },
  DUMPING: {
    problemLabel: "Illegal Dumping Detected",
    priority: "MEDIUM",
    severity: 55,
    confidence: 86,
    departmentLabel: "Municipal Sanitation Department",
    department: "Sanitation",
    inCharge: "Sanitation Department — Enforcement Officer",
    explanationEn: "The image shows debris and waste dumped in a public space that is not an authorized collection point.",
    explanationTe: "చిత్రంలో అనధికార ప్రదేశంలో వ్యర్థాలు మరియు శిథిలాలు పడేసినట్లు కనిపిస్తోంది.",
    complaintEn: {
      subject: "Request for removal of illegally dumped waste",
      description: "Waste and debris have been dumped in a public space that is not an authorized collection point.",
      impact: "Unsanitary conditions, blocked public space, and potential encouragement of further dumping.",
      action: "Removal of the dumped waste and enforcement action by the Sanitation Department.",
    },
    complaintTe: {
      subject: "అక్రమంగా పడేసిన వ్యర్థాలను తొలగించడానికి అభ్యర్థన",
      description: "అధికారం లేని ప్రదేశంలో వ్యర్థాలు మరియు శిథిలాలు పడేయబడ్డాయి.",
      impact: "అపరిశుభ్ర పరిస్థితులు, బహిరంగ స్థలం అడ్డుపడటం మరియు మరింత డంపింగ్‌కు ప్రోత్సాహం.",
      action: "సానిటేషన్ విభాగం వ్యర్థాలను తొలగించి తగిన చర్య తీసుకోవాలి.",
    },
  },
  INFRASTRUCTURE: {
    problemLabel: "Public Infrastructure Damage Detected",
    priority: "LOW",
    severity: 35,
    confidence: 84,
    departmentLabel: "Municipal Public Works Department",
    department: "Public Works",
    inCharge: "Public Works Department — Maintenance In-charge",
    explanationEn: "The image shows damage to shared public infrastructure such as a footpath or signage.",
    explanationTe: "చిత్రంలో పాదచారుల మార్గం లేదా సూచిక వంటి ప్రజా మౌలిక సదుపాయాలకు నష్టం కనిపిస్తోంది.",
    complaintEn: {
      subject: "Request for repair of damaged public infrastructure",
      description: "Public infrastructure in this area has been damaged and needs repair to remain safe for public use.",
      impact: "Reduced safety and accessibility for pedestrians in the area.",
      action: "Inspection and repair by the Public Works Department.",
    },
    complaintTe: {
      subject: "దెబ్బతిన్న ప్రజా మౌలిక సదుపాయాల మరమ్మతు కోసం అభ్యర్థన",
      description: "ఈ ప్రాంతంలోని ప్రజా మౌలిక సదుపాయం దెబ్బతింది మరియు సురక్షితంగా ఉండేందుకు మరమ్మతు అవసరం.",
      impact: "పాదచారులకు భద్రత మరియు ప్రాప్యత తగ్గడం.",
      action: "పబ్లిక్ వర్క్స్ విభాగం తనిఖీ చేసి మరమ్మతు చేయాలి.",
    },
  },
  OTHER: {
    problemLabel: "Civic Issue Detected",
    priority: "MEDIUM",
    severity: 50,
    confidence: 80,
    departmentLabel: "General Administration Department",
    department: "Public Works",
    inCharge: "General Administration — Duty Officer",
    explanationEn: "The image shows a civic issue that doesn't fit a standard category and has been flagged for manual review.",
    explanationTe: "చిత్రంలో ప్రామాణిక వర్గానికి సరిపోని పౌర సమస్య కనిపిస్తోంది, ఇది మాన్యువల్ సమీక్ష కోసం గుర్తించబడింది.",
    complaintEn: {
      subject: "Report of a civic issue requiring attention",
      description: "A civic issue has been reported in this area that requires review by the concerned department.",
      impact: "Inconvenience and potential risk to residents until addressed.",
      action: "Review and appropriate action by the concerned department.",
    },
    complaintTe: {
      subject: "దృష్టి అవసరమైన పౌర సమస్య నివేదిక",
      description: "ఈ ప్రాంతంలో సంబంధిత విభాగం సమీక్షించాల్సిన పౌర సమస్య నివేదించబడింది.",
      impact: "పరిష్కరించే వరకు నివాసితులకు అసౌకర్యం మరియు సంభావ్య ప్రమాదం.",
      action: "సంబంధిత విభాగం సమీక్షించి తగిన చర్య తీసుకోవాలి.",
    },
  },
};
