import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, LayoutDashboard } from "lucide-react";
import { ComplaintDocument, type ComplaintFields } from "@/components/cards/ComplaintDocument";
import { CTAButton } from "@/components/ui/CTAButton";
import { ReportProgress } from "@/components/report/ReportProgress";
import { categoryAIPresets } from "@/lib/ai-presets";
import { locationComplaintSummary, locationDocumentLines } from "@/lib/location-format";
import { getReportDetail } from "@/lib/data/report-detail";

export default async function ComplaintPage({
  searchParams,
}: {
  searchParams: Promise<{ reportId?: string }>;
}) {
  const { reportId } = await searchParams;
  if (!reportId) notFound();

  const report = await getReportDetail(reportId);
  if (!report) notFound();

  const preset = categoryAIPresets[report.category];
  const locationLabel = locationComplaintSummary(report.location).join("\n");
  const locationFullDetails = locationDocumentLines(report.location).join("\n");

  // Phase 6A: real AI-generated subject/impact/action, produced in the same
  // Gemini call as the rest of the analysis (src/lib/ai.ts) and grounded
  // only in the report's own description/category/image — no invented
  // dates, officials, or incident history. Falls back to the static
  // per-category template only for reports analyzed before this field
  // existed, or if AI analysis never completed for this report.
  const aiComplaint = report.aiAnalysis?.extended;
  const usingAiComplaint = Boolean(aiComplaint);

  const contentEn: ComplaintFields = {
    subject: aiComplaint?.complaint_subject ?? preset.complaintEn.subject,
    description: report.description,
    location: locationLabel,
    impact: aiComplaint?.complaint_impact ?? preset.complaintEn.impact,
    action: aiComplaint?.complaint_action ?? preset.complaintEn.action,
  };

  const contentTe: ComplaintFields = {
    subject: preset.complaintTe.subject,
    description: preset.complaintTe.description,
    location: locationLabel,
    impact: preset.complaintTe.impact,
    action: preset.complaintTe.action,
  };

  return (
    <div className="bg-surface-muted">
      <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8">
        <Link
          href={`/report/analysis?reportId=${report.id}`}
          className="inline-flex items-center gap-1.5 text-sm font-medium text-foreground-muted hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" aria-hidden="true" />
          Back to analysis
        </Link>

        <div className="mt-6 text-center">
          <span className="text-sm font-semibold text-civic-700">Complaint Generator</span>
          <h1 className="mt-1 text-3xl font-semibold tracking-tight text-foreground">
            Your complaint is ready.
          </h1>
          <p className="mt-2 text-sm text-foreground-muted">
            Review, edit if needed, then take it to your dashboard to track progress.
          </p>
          <div className="mt-4 flex justify-center">
            <ReportProgress current={3} />
          </div>
        </div>

        <div className="mt-8">
          <ComplaintDocument
            issueId={report.id.slice(0, 8).toUpperCase()}
            contentEn={contentEn}
            contentTe={contentTe}
            locationFullDetails={locationFullDetails}
            imageSrc={report.media[0]?.url ?? "/images/hero-pothole.jpg"}
            imageAlt="Photo evidence attached to your complaint"
            footerNote={
              usingAiComplaint
                ? "Your description and location are pulled from your real report. Subject, impact, and requested-action wording were generated by AI from your report — review before submitting."
                : "Your description and location are pulled from your real report. Subject, impact, and requested-action wording use a category template — AI analysis for this report didn't produce a complaint draft."
            }
            descriptionNote="Telugu translation isn't connected to a live translation service yet — Telugu fields use template text."
            afterActions={
              <CTAButton href="/dashboard" size="md" className="mt-1 w-full justify-center">
                <LayoutDashboard className="mr-1.5 h-4 w-4" />
                Go to Dashboard
              </CTAButton>
            }
          />
        </div>
      </div>
    </div>
  );
}
